/*
Deployment script for ztest

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "ztest"
:setvar DefaultFilePrefix "ztest"
:setvar DefaultDataPath "/var/opt/mssql/data/"
:setvar DefaultLogPath "/var/opt/mssql/data/"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating Schema [users]...';


GO
CREATE SCHEMA [users]
    AUTHORIZATION [dbo];


GO
PRINT N'Creating Table [users].[Users]...';


GO
CREATE TABLE [users].[Users] (
    [Id]        INT            IDENTITY (1, 1) NOT NULL,
    [Name]      NVARCHAR (100) NOT NULL,
    [Email]     NVARCHAR (255) NOT NULL,
    [CreatedAt] DATETIME       NULL,
    CONSTRAINT [PK__Users__3214EC07F18B6ED4] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UQ__Users__A9D105342171F50B] UNIQUE NONCLUSTERED ([Email] ASC)
);


GO
PRINT N'Creating Default Constraint unnamed constraint on [users].[Users]...';


GO
ALTER TABLE [users].[Users]
    ADD DEFAULT (getdate()) FOR [CreatedAt];


GO
PRINT N'Altering Procedure [dbo].[GetUsers]...';


GO
ALTER procedure dbo.GetUsers
as
begin
    select * from dbo.Users 
end;
GO
PRINT N'Update complete.';


GO
